services:
  - type: web
    name: python-pwd-service
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    region: singapore
